/**
 * @warning This file is auto-generated. Do not edit directly.
 * @brief Grapheme cluster break property data.
 * @ref Unicode UCD - Generated by unicode.generate.py
 * @version 1
 * @date 2025-08-02
 */

#ifndef UTF8_GRAPHEME_DATA_H
#define UTF8_GRAPHEME_DATA_H

#include <stddef.h>
#include <stdint.h>

typedef enum GraphemeClass {
    GCB_UNDEFINED = 0,
    GCB_PREPEND = 1,
    GCB_CR = 2,
    GCB_LF = 3,
    GCB_CONTROL = 4,
    GCB_EXTEND = 5,
    GCB_SPACINGMARK = 6,
    GCB_L = 7,
    GCB_V = 8,
    GCB_T = 9,
    GCB_LV = 10,
    GCB_LVT = 11,
    GCB_ZWJ = 12,
    GCB_EMOJI = 13,
    GCB_EMOJI_PRESENTATION = 14,
    GCB_EMOJI_MODIFIER_BASE = 15,
    GCB_EMOJI_COMPONENT = 16,
    GCB_EXTENDED_PICTOGRAPHIC = 17,
    GCB_DIACRITIC = 18,
} GraphemeClass;

typedef struct Grapheme {
    uint32_t lo, hi;
    GraphemeClass cls;
} Grapheme;

extern const Grapheme graphemes[];
extern const size_t GRAPHEME_SIZE;

#endif // UTF8_GRAPHEME_DATA_H
