/**
 * @warning This file is auto-generated. Do not edit directly.
 * @brief Grapheme cluster break property data.
 * @ref Unicode UCD - Generated by unicode.grapheme.py
 * @version 1
 * @date 2025-08-03
 */

#ifndef UTF8_GRAPHEME_DATA_H
#define UTF8_GRAPHEME_DATA_H

#include <stddef.h>
#include <stdint.h>

typedef enum UTF8GraphemeClass {
    GCB_UNDEFINED = 0,
    GCB_PREPEND = 1,
    GCB_CR = 2,
    GCB_LF = 3,
    GCB_CONTROL = 4,
    GCB_EXTEND = 5,
    GCB_SPACINGMARK = 6,
    GCB_REGIONAL_INDICATOR = 7,
    GCB_L = 8,
    GCB_V = 9,
    GCB_T = 10,
    GCB_LV = 11,
    GCB_LVT = 12,
    GCB_ZWJ = 13,
    GCB_EMOJI = 14,
    GCB_EMOJI_PRESENTATION = 15,
    GCB_EMOJI_MODIFIER_BASE = 16,
    GCB_EMOJI_COMPONENT = 17,
    GCB_EXTENDED_PICTOGRAPHIC = 18,
    GCB_BIDI_CONTROL = 19,
    GCB_EXTENDER = 20,
    GCB_OTHER_GRAPHEME_EXTEND = 21,
    GCB_DIACRITIC = 22,
    GCB_PREPENDED_CONCATENATION_MARK = 23,
    GCB_MODIFIER_COMBINING_MARK = 24,
} UTF8GraphemeClass;

typedef struct UTF8Grapheme {
    uint32_t lo, hi;
    UTF8GraphemeClass cls;
} UTF8Grapheme;

extern const UTF8Grapheme graphemes[];
extern const size_t UTF8_GRAPHEME_SIZE;

#endif // UTF8_GRAPHEME_DATA_H
